from __future__ import annotations

import shlex
from dataclasses import dataclass
from datetime import datetime

from modules.vllm_profiles import VllmProfile, build_vllm_command, cache_env_preview_lines


@dataclass(frozen=True)
class VllmScriptPreview:
    ok: bool
    script_text: str
    messages: list[str]


def build_vllm_script_preview(profile: VllmProfile, *, timestamp: str | None = None) -> VllmScriptPreview:
    command, messages = build_vllm_command(profile)
    if command is None:
        return VllmScriptPreview(False, "", messages)

    created_at = timestamp or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    env_lines = []
    for line in cache_env_preview_lines(profile):
        key, value = line.split("=", 1)
        env_lines.append(f"export {key}={shlex.quote(value)}")

    script_text = "\n".join(
        [
            "#!/usr/bin/env bash",
            "# vLLM serve script",
            f"# generated: {created_at}",
            "# generated by llama-suite",
            "",
            "set -euo pipefail",
            "",
            *env_lines,
            "",
            "exec " + shlex.join(command),
            "",
        ]
    )
    return VllmScriptPreview(True, script_text, ["vLLM script preview generated"])
