from __future__ import annotations

import shlex
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from modules.vllm.profiles import VllmProfile, build_vllm_command, cache_env_preview_lines


DEFAULT_VLLM_SCRIPT_DIR = "~/.local/state/llama-suite/scripts/vllm"


@dataclass(frozen=True)
class VllmScriptPreview:
    ok: bool
    script_text: str
    messages: list[str]


def build_vllm_script_preview(profile: VllmProfile, *, timestamp: str | None = None) -> VllmScriptPreview:
    command, messages = build_vllm_command(profile)
    if command is None:
        return VllmScriptPreview(False, "", messages)

    created_at = timestamp or datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    env_lines = []
    for line in cache_env_preview_lines(profile):
        key, value = line.split("=", 1)
        env_lines.append(f"export {key}={shlex.quote(value)}")

    script_text = "\n".join(
        [
            "#!/usr/bin/env bash",
            "# vLLM serve script",
            f"# generated: {created_at}",
            "# generated by llama-suite",
            "",
            "set -euo pipefail",
            "",
            *env_lines,
            "",
            "exec " + shlex.join(command),
            "",
        ]
    )
    return VllmScriptPreview(True, script_text, ["vLLM script preview generated"])


@dataclass(frozen=True)
class VllmScriptSaveResult:
    ok: bool
    script_path: str | None
    messages: list[str]


def save_vllm_script(
    profile: VllmProfile,
    *,
    script_id: str = "custom-draft",
    scripts_dir: str | Path | None = None,
    timestamp: str | None = None,
) -> VllmScriptSaveResult:
    preview = build_vllm_script_preview(profile, timestamp=timestamp)
    if not preview.ok:
        return VllmScriptSaveResult(False, None, preview.messages)

    target_dir = Path(scripts_dir or DEFAULT_VLLM_SCRIPT_DIR).expanduser()
    script_name = f"{_safe_name(script_id)}.sh"
    try:
        target_dir.mkdir(parents=True, exist_ok=True)
        script_path = _collision_free_path(target_dir / script_name)
        script_path.write_text(preview.script_text)
        script_path.chmod(0o755)
    except Exception as exc:
        return VllmScriptSaveResult(False, None, [f"vLLM script save failed: {exc}"])

    return VllmScriptSaveResult(True, str(script_path), [f"vLLM script saved: {script_path}"])


def _collision_free_path(path: Path) -> Path:
    if not path.exists():
        return path
    counter = 2
    while True:
        candidate = path.with_name(f"{path.stem}__{counter}{path.suffix}")
        if not candidate.exists():
            return candidate
        counter += 1


def _safe_name(value: str) -> str:
    text = str(value or "custom-draft").strip()
    return "".join(char if char.isalnum() or char in "-_." else "-" for char in text) or "custom-draft"
